### ISSUE TITLE
Content review: Home page

### ISSUE THREAD

**Issue by darptab** [Office-of-Digital-Services/cagovportal#108]
https://docs.google.com/document/d/1etkuWTQz2tijQ9DG7SfK0fxDrGcZh6TO-Lbu3LdzPLs/edit?usp=sharing

**Comment by extinah** [comment]
Christina reviewed. Nice! Looks great. Minor comments.

**Comment by artkho** [comment]
@artkho reviewed - comments in the doc.

**Comment by darptab** [comment]
Validated!
