### ISSUE TITLE
Look into "Get a high school diploma" service

### ISSUE THREAD

**Issue by darptab** [Office-of-Digital-Services/cagovportal#170]

**Comment by extinah** [comment]
The link when you launch the service is a broken page - Christina and Art to investigate.

**Comment by extinah** [comment]
Options;
https://www.cde.ca.gov/ci/gs/hs/
https://www.cde.ca.gov/ta/tg/gd/

@artkho  Maybe we can ask Steven to reach out and validate with the CDE contact.

**Comment by extinah** [comment]
@darptab let's use this one: https://www.cde.ca.gov/ta/tg/gd/
