### ISSUE TITLE
Define pages and page templates (can be flexible)

### ISSUE THREAD

**Issue by nguyenalicea** [Office-of-Digital-Services/cagovportal#26]

**Comment by nguyenalicea** [comment]
Non-dynamic pages below. Remaining pages are dynamic within State Entity App. 

https://www.ca.gov/
https://www.ca.gov/accessibility/
https://www.ca.gov/accessibility/website-accessibility-certification.html
https://www.ca.gov/agenciesall/
https://www.ca.gov/agencysearch/
https://www.ca.gov/contact/
https://www.ca.gov/doingbusiness/
https://www.ca.gov/government/
https://www.ca.gov/help/
https://www.ca.gov/learning/
https://www.ca.gov/living/
https://www.ca.gov/privacy-policy/
https://www.ca.gov/serp/
https://www.ca.gov/services/
https://www.ca.gov/sitemap/
https://www.ca.gov/translate/
https://www.ca.gov/use/
https://www.ca.gov/visiting/
https://www.ca.gov/website-feedback/
https://www.ca.gov/working/

**Comment by kkoryaka** [comment]
https://cdt.miro.com/app/board/uHjVOfvUmok=/
New IA
