### ISSUE TITLE
Set up initial State Web Template website that is using eleventy framework

### ISSUE THREAD

**Issue by artkho** [Office-of-Digital-Services/cagovportal#4]
Set up eleventy State Web Template website framework that will be used by this ca.gov portal and make initial commit to this (cagivportal) repo

**Comment by kkoryaka** [comment]
Created dev branch and made initial commit of the eleventy framework. https://github.com/Office-of-Digital-Services/cagovportal/tree/dev 

This branch will trigger development slot release in azure every time the dev branch is updated.
